updates to both DIH and DIHService
smart-data-models/dataModel.DigitalInnovationHub pull request #1
Opened 2022-08-05 14:42 UTC by manfredipist

2022-08-16 15:39 UTC, albertoabellagarcia requested changes
better to hold a session live next few days to approve/reject some of the proposed changes. 
https://calendly.com/smartdatamodels

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHub/examples/example-normalized.json
>  		"value": "https://www.sample-dih.com/"
this is the NGSIv2 file. These changes are NGSI -LD

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHub/examples/example-normalized.jsonld
>  	"relation": {
'array' is not a NGSI-LD type. so it cannot be there.

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHub/examples/example.json
>  	"relation": [
Although this is a key values file, the relation is an object, therefore subproperties have to appear.

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHub/examples/example.jsonld
>  	"relation": [
same as previous example

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHub/schema.json
>            "description": "Property. [URL](https://schema.org/URL). Website of the Digital Innovation Hub."
why this change? it is also valid, and the previous model was more general. Need justification.

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHub/schema.json
> +          "description": "Property. [URL](https://schema.org/URL). URL of the logo of the Digital Innovation Hub."
the markdown cannot be used inside the description of the attribute. The right way to do it is Model:'xxxxx', (see contribution manual. https://bit.ly/contribution_manual )

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHub/schema.json
> +          "description": "Property. [PostalAddress](https://schema.org/PostalAddress). PostalAddress of the Digital Innovation Hub."
same markdown cannot be used here.

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHub/schema.json
> +          "description": "Property. [StructuredValue](https://schema.org/StructuredValue). Relations of the Digital Innovation Hub Service.",
markdown is not available here.

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHubService/examples/example-normalized.json
>  	"serviceImage": {
the change in the format has to be justified

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHubService/examples/example-normalized.json
> +		"type": "Property",
This is not NGSIv2 but NGSI-LD. this change is misplaced.

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHubService/examples/example-normalized.json
> +		"type": "array",
This is not compliant with the current schema.

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHubService/examples/example-normalized.jsonld
>  	"serviceImage": {
already commented same change

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHubService/examples/example-normalized.jsonld
> +		"type": "array",
already commented same change

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHubService/examples/example.json
> +    "serviceImage": "https://www.sample-dih.com/logo.png",
justify change.

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHubService/examples/example.json
> +    "relation": [
not compliant with schema

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHubService/examples/example.jsonld
> +    "serviceImage": "https://www.sample-dih.com/logo.png",
same as previous

2022-08-16 15:39 UTC, albertoabellagarcia commented on DigitalInnovationHubService/schema.json
>          "serviceImage": {
Why this change?

2022-09-19 17:41 UTC, albertoabellagarcia requested changes
AS far as I know you di not solve the comments, right?

2022-09-20 11:00 UTC, manfredipist commented
Hi @albertoabellagarcia , could you please recheck the model ? Thanks

2022-09-20 11:57 UTC, albertoabellagarcia approved these changes
I will fix the issues that remain because it takes me more time to send you than to fix them

2022-09-20 11:57 UTC, albertoabellagarcia commented on DigitalInnovationHub/examples/example-normalized.json
> +		"type": "GeoProperty",
this is ngsi-ld in a ngsiv2 payload (eventually it would work) but it does not look like a ngsiv2 payload

2022-09-20 11:57 UTC, albertoabellagarcia commented on DigitalInnovationHubService/schema.json
>      },
I don't think this is a good idea to remove Location-commons unless location commons is elsewhere

2022-09-20 11:57 UTC, merged

2022-09-20 16:08 UTC, albertoabellagarcia commented
Already corrected and published

2022-09-20 16:31 UTC, albertoabellagarcia reviewed
I have republished the model this morning. Are these changes previous or after the new version? I think that they are before them and therefore they are already available, but please let me know. 

Best

2022-09-21 10:05 UTC, walterwootz commented
Hi @albertoabellagarcia, I'm contributing with @manfredipist on this model. What do you mean with:
> Are these changes previous or after the new version?

I see your merge, thank you for your help and attention. Do you think the model is now ok?

2022-09-21 10:05 UTC, walterwootz commented on DigitalInnovationHubService/schema.json
>      },
removed because location info is not needed at the moment on this model